/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmBreveRouteImport } from './routes/em-breve'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PagarTokenRouteImport } from './routes/pagar.$token'
import { Route as AppTreinosRouteImport } from './routes/app.treinos'
import { Route as AppRankingRouteImport } from './routes/app.ranking'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMetasRouteImport } from './routes/app.metas'
import { Route as AppDietaRouteImport } from './routes/app.dieta'
import { Route as AppAvaliacaoRouteImport } from './routes/app.avaliacao'
import { Route as AdminTreinosRouteImport } from './routes/admin.treinos'
import { Route as AdminProfessoresRouteImport } from './routes/admin.professores'
import { Route as AdminPresencasRouteImport } from './routes/admin.presencas'
import { Route as AdminPlanosSemanaisRouteImport } from './routes/admin.planos-semanais'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminPagamentosConfigRouteImport } from './routes/admin.pagamentos-config'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminExerciciosRouteImport } from './routes/admin.exercicios'
import { Route as AdminEquipamentosRouteImport } from './routes/admin.equipamentos'
import { Route as AdminDietasRouteImport } from './routes/admin.dietas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminAtribuirTreinosRouteImport } from './routes/admin.atribuir-treinos'
import { Route as AdminAssinaturasRouteImport } from './routes/admin.assinaturas'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as ApiPublicWebhooksStoneRouteImport } from './routes/api/public.webhooks-stone'
import { Route as ApiMeRolesRouteImport } from './routes/api/me.roles'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin.settings'
import { Route as ApiAdminPaymentsSubscriptionRouteImport } from './routes/api/admin.payments-subscription'
import { Route as ApiAdminPaymentsLinkRouteImport } from './routes/api/admin.payments-link'
import { Route as ApiAdminPaymentsConfigRouteImport } from './routes/api/admin.payments-config'
import { Route as ApiAdminBrandingUploadRouteImport } from './routes/api/admin.branding-upload'
import { Route as ApiPublicPaymentsLinkTokenRouteImport } from './routes/api/public.payments-link.$token'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmBreveRoute = EmBreveRouteImport.update({
  id: '/em-breve',
  path: '/em-breve',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PagarTokenRoute = PagarTokenRouteImport.update({
  id: '/pagar/$token',
  path: '/pagar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTreinosRoute = AppTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppDietaRoute = AppDietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacaoRoute = AppAvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => AppRoute,
} as any)
const AdminTreinosRoute = AdminTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessoresRoute = AdminProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPresencasRoute = AdminPresencasRouteImport.update({
  id: '/presencas',
  path: '/presencas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosSemanaisRoute = AdminPlanosSemanaisRouteImport.update({
  id: '/planos-semanais',
  path: '/planos-semanais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosConfigRoute = AdminPagamentosConfigRouteImport.update({
  id: '/pagamentos-config',
  path: '/pagamentos-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExerciciosRoute = AdminExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipamentosRoute = AdminEquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDietasRoute = AdminDietasRouteImport.update({
  id: '/dietas',
  path: '/dietas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtribuirTreinosRoute = AdminAtribuirTreinosRouteImport.update({
  id: '/atribuir-treinos',
  path: '/atribuir-treinos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWebhooksStoneRoute = ApiPublicWebhooksStoneRouteImport.update({
  id: '/api/public/webhooks-stone',
  path: '/api/public/webhooks-stone',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRolesRoute = ApiMeRolesRouteImport.update({
  id: '/api/me/roles',
  path: '/api/me/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentsSubscriptionRoute =
  ApiAdminPaymentsSubscriptionRouteImport.update({
    id: '/api/admin/payments-subscription',
    path: '/api/admin/payments-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPaymentsLinkRoute = ApiAdminPaymentsLinkRouteImport.update({
  id: '/api/admin/payments-link',
  path: '/api/admin/payments-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentsConfigRoute = ApiAdminPaymentsConfigRouteImport.update({
  id: '/api/admin/payments-config',
  path: '/api/admin/payments-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBrandingUploadRoute = ApiAdminBrandingUploadRouteImport.update({
  id: '/api/admin/branding-upload',
  path: '/api/admin/branding-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsLinkTokenRoute =
  ApiPublicPaymentsLinkTokenRouteImport.update({
    id: '/api/public/payments-link/$token',
    path: '/api/public/payments-link/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/em-breve': typeof EmBreveRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/atribuir-treinos': typeof AdminAtribuirTreinosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dietas': typeof AdminDietasRoute
  '/admin/equipamentos': typeof AdminEquipamentosRoute
  '/admin/exercicios': typeof AdminExerciciosRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pagamentos-config': typeof AdminPagamentosConfigRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/planos-semanais': typeof AdminPlanosSemanaisRoute
  '/admin/presencas': typeof AdminPresencasRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/app/avaliacao': typeof AppAvaliacaoRoute
  '/app/dieta': typeof AppDietaRoute
  '/app/metas': typeof AppMetasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/treinos': typeof AppTreinosRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/admin/branding-upload': typeof ApiAdminBrandingUploadRoute
  '/api/admin/payments-config': typeof ApiAdminPaymentsConfigRoute
  '/api/admin/payments-link': typeof ApiAdminPaymentsLinkRoute
  '/api/admin/payments-subscription': typeof ApiAdminPaymentsSubscriptionRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/me/roles': typeof ApiMeRolesRoute
  '/api/public/webhooks-stone': typeof ApiPublicWebhooksStoneRoute
  '/api/public/payments-link/$token': typeof ApiPublicPaymentsLinkTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/em-breve': typeof EmBreveRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/atribuir-treinos': typeof AdminAtribuirTreinosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dietas': typeof AdminDietasRoute
  '/admin/equipamentos': typeof AdminEquipamentosRoute
  '/admin/exercicios': typeof AdminExerciciosRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pagamentos-config': typeof AdminPagamentosConfigRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/planos-semanais': typeof AdminPlanosSemanaisRoute
  '/admin/presencas': typeof AdminPresencasRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/app/avaliacao': typeof AppAvaliacaoRoute
  '/app/dieta': typeof AppDietaRoute
  '/app/metas': typeof AppMetasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/treinos': typeof AppTreinosRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/admin/branding-upload': typeof ApiAdminBrandingUploadRoute
  '/api/admin/payments-config': typeof ApiAdminPaymentsConfigRoute
  '/api/admin/payments-link': typeof ApiAdminPaymentsLinkRoute
  '/api/admin/payments-subscription': typeof ApiAdminPaymentsSubscriptionRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/me/roles': typeof ApiMeRolesRoute
  '/api/public/webhooks-stone': typeof ApiPublicWebhooksStoneRoute
  '/api/public/payments-link/$token': typeof ApiPublicPaymentsLinkTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/em-breve': typeof EmBreveRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/assinaturas': typeof AdminAssinaturasRoute
  '/admin/atribuir-treinos': typeof AdminAtribuirTreinosRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dietas': typeof AdminDietasRoute
  '/admin/equipamentos': typeof AdminEquipamentosRoute
  '/admin/exercicios': typeof AdminExerciciosRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/pagamentos-config': typeof AdminPagamentosConfigRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/planos-semanais': typeof AdminPlanosSemanaisRoute
  '/admin/presencas': typeof AdminPresencasRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/app/avaliacao': typeof AppAvaliacaoRoute
  '/app/dieta': typeof AppDietaRoute
  '/app/metas': typeof AppMetasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/treinos': typeof AppTreinosRoute
  '/pagar/$token': typeof PagarTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/admin/branding-upload': typeof ApiAdminBrandingUploadRoute
  '/api/admin/payments-config': typeof ApiAdminPaymentsConfigRoute
  '/api/admin/payments-link': typeof ApiAdminPaymentsLinkRoute
  '/api/admin/payments-subscription': typeof ApiAdminPaymentsSubscriptionRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/me/roles': typeof ApiMeRolesRoute
  '/api/public/webhooks-stone': typeof ApiPublicWebhooksStoneRoute
  '/api/public/payments-link/$token': typeof ApiPublicPaymentsLinkTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/em-breve'
    | '/login'
    | '/ranking'
    | '/admin/alunos'
    | '/admin/assinaturas'
    | '/admin/atribuir-treinos'
    | '/admin/configuracoes'
    | '/admin/dietas'
    | '/admin/equipamentos'
    | '/admin/exercicios'
    | '/admin/pagamentos'
    | '/admin/pagamentos-config'
    | '/admin/planos'
    | '/admin/planos-semanais'
    | '/admin/presencas'
    | '/admin/professores'
    | '/admin/treinos'
    | '/app/avaliacao'
    | '/app/dieta'
    | '/app/metas'
    | '/app/perfil'
    | '/app/ranking'
    | '/app/treinos'
    | '/pagar/$token'
    | '/admin/'
    | '/app/'
    | '/api/admin/branding-upload'
    | '/api/admin/payments-config'
    | '/api/admin/payments-link'
    | '/api/admin/payments-subscription'
    | '/api/admin/settings'
    | '/api/me/roles'
    | '/api/public/webhooks-stone'
    | '/api/public/payments-link/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/em-breve'
    | '/login'
    | '/ranking'
    | '/admin/alunos'
    | '/admin/assinaturas'
    | '/admin/atribuir-treinos'
    | '/admin/configuracoes'
    | '/admin/dietas'
    | '/admin/equipamentos'
    | '/admin/exercicios'
    | '/admin/pagamentos'
    | '/admin/pagamentos-config'
    | '/admin/planos'
    | '/admin/planos-semanais'
    | '/admin/presencas'
    | '/admin/professores'
    | '/admin/treinos'
    | '/app/avaliacao'
    | '/app/dieta'
    | '/app/metas'
    | '/app/perfil'
    | '/app/ranking'
    | '/app/treinos'
    | '/pagar/$token'
    | '/admin'
    | '/app'
    | '/api/admin/branding-upload'
    | '/api/admin/payments-config'
    | '/api/admin/payments-link'
    | '/api/admin/payments-subscription'
    | '/api/admin/settings'
    | '/api/me/roles'
    | '/api/public/webhooks-stone'
    | '/api/public/payments-link/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/em-breve'
    | '/login'
    | '/ranking'
    | '/admin/alunos'
    | '/admin/assinaturas'
    | '/admin/atribuir-treinos'
    | '/admin/configuracoes'
    | '/admin/dietas'
    | '/admin/equipamentos'
    | '/admin/exercicios'
    | '/admin/pagamentos'
    | '/admin/pagamentos-config'
    | '/admin/planos'
    | '/admin/planos-semanais'
    | '/admin/presencas'
    | '/admin/professores'
    | '/admin/treinos'
    | '/app/avaliacao'
    | '/app/dieta'
    | '/app/metas'
    | '/app/perfil'
    | '/app/ranking'
    | '/app/treinos'
    | '/pagar/$token'
    | '/admin/'
    | '/app/'
    | '/api/admin/branding-upload'
    | '/api/admin/payments-config'
    | '/api/admin/payments-link'
    | '/api/admin/payments-subscription'
    | '/api/admin/settings'
    | '/api/me/roles'
    | '/api/public/webhooks-stone'
    | '/api/public/payments-link/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  EmBreveRoute: typeof EmBreveRoute
  LoginRoute: typeof LoginRoute
  RankingRoute: typeof RankingRoute
  PagarTokenRoute: typeof PagarTokenRoute
  ApiAdminBrandingUploadRoute: typeof ApiAdminBrandingUploadRoute
  ApiAdminPaymentsConfigRoute: typeof ApiAdminPaymentsConfigRoute
  ApiAdminPaymentsLinkRoute: typeof ApiAdminPaymentsLinkRoute
  ApiAdminPaymentsSubscriptionRoute: typeof ApiAdminPaymentsSubscriptionRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiMeRolesRoute: typeof ApiMeRolesRoute
  ApiPublicWebhooksStoneRoute: typeof ApiPublicWebhooksStoneRoute
  ApiPublicPaymentsLinkTokenRoute: typeof ApiPublicPaymentsLinkTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-breve': {
      id: '/em-breve'
      path: '/em-breve'
      fullPath: '/em-breve'
      preLoaderRoute: typeof EmBreveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pagar/$token': {
      id: '/pagar/$token'
      path: '/pagar/$token'
      fullPath: '/pagar/$token'
      preLoaderRoute: typeof PagarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/treinos': {
      id: '/app/treinos'
      path: '/treinos'
      fullPath: '/app/treinos'
      preLoaderRoute: typeof AppTreinosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ranking': {
      id: '/app/ranking'
      path: '/ranking'
      fullPath: '/app/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dieta': {
      id: '/app/dieta'
      path: '/dieta'
      fullPath: '/app/dieta'
      preLoaderRoute: typeof AppDietaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/avaliacao': {
      id: '/app/avaliacao'
      path: '/avaliacao'
      fullPath: '/app/avaliacao'
      preLoaderRoute: typeof AppAvaliacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/treinos': {
      id: '/admin/treinos'
      path: '/treinos'
      fullPath: '/admin/treinos'
      preLoaderRoute: typeof AdminTreinosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professores': {
      id: '/admin/professores'
      path: '/professores'
      fullPath: '/admin/professores'
      preLoaderRoute: typeof AdminProfessoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/presencas': {
      id: '/admin/presencas'
      path: '/presencas'
      fullPath: '/admin/presencas'
      preLoaderRoute: typeof AdminPresencasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos-semanais': {
      id: '/admin/planos-semanais'
      path: '/planos-semanais'
      fullPath: '/admin/planos-semanais'
      preLoaderRoute: typeof AdminPlanosSemanaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos-config': {
      id: '/admin/pagamentos-config'
      path: '/pagamentos-config'
      fullPath: '/admin/pagamentos-config'
      preLoaderRoute: typeof AdminPagamentosConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exercicios': {
      id: '/admin/exercicios'
      path: '/exercicios'
      fullPath: '/admin/exercicios'
      preLoaderRoute: typeof AdminExerciciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipamentos': {
      id: '/admin/equipamentos'
      path: '/equipamentos'
      fullPath: '/admin/equipamentos'
      preLoaderRoute: typeof AdminEquipamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dietas': {
      id: '/admin/dietas'
      path: '/dietas'
      fullPath: '/admin/dietas'
      preLoaderRoute: typeof AdminDietasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atribuir-treinos': {
      id: '/admin/atribuir-treinos'
      path: '/atribuir-treinos'
      fullPath: '/admin/atribuir-treinos'
      preLoaderRoute: typeof AdminAtribuirTreinosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinaturas': {
      id: '/admin/assinaturas'
      path: '/assinaturas'
      fullPath: '/admin/assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/webhooks-stone': {
      id: '/api/public/webhooks-stone'
      path: '/api/public/webhooks-stone'
      fullPath: '/api/public/webhooks-stone'
      preLoaderRoute: typeof ApiPublicWebhooksStoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/roles': {
      id: '/api/me/roles'
      path: '/api/me/roles'
      fullPath: '/api/me/roles'
      preLoaderRoute: typeof ApiMeRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payments-subscription': {
      id: '/api/admin/payments-subscription'
      path: '/api/admin/payments-subscription'
      fullPath: '/api/admin/payments-subscription'
      preLoaderRoute: typeof ApiAdminPaymentsSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payments-link': {
      id: '/api/admin/payments-link'
      path: '/api/admin/payments-link'
      fullPath: '/api/admin/payments-link'
      preLoaderRoute: typeof ApiAdminPaymentsLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payments-config': {
      id: '/api/admin/payments-config'
      path: '/api/admin/payments-config'
      fullPath: '/api/admin/payments-config'
      preLoaderRoute: typeof ApiAdminPaymentsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/branding-upload': {
      id: '/api/admin/branding-upload'
      path: '/api/admin/branding-upload'
      fullPath: '/api/admin/branding-upload'
      preLoaderRoute: typeof ApiAdminBrandingUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments-link/$token': {
      id: '/api/public/payments-link/$token'
      path: '/api/public/payments-link/$token'
      fullPath: '/api/public/payments-link/$token'
      preLoaderRoute: typeof ApiPublicPaymentsLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AdminAtribuirTreinosRoute: typeof AdminAtribuirTreinosRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDietasRoute: typeof AdminDietasRoute
  AdminEquipamentosRoute: typeof AdminEquipamentosRoute
  AdminExerciciosRoute: typeof AdminExerciciosRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPagamentosConfigRoute: typeof AdminPagamentosConfigRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminPlanosSemanaisRoute: typeof AdminPlanosSemanaisRoute
  AdminPresencasRoute: typeof AdminPresencasRoute
  AdminProfessoresRoute: typeof AdminProfessoresRoute
  AdminTreinosRoute: typeof AdminTreinosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AdminAtribuirTreinosRoute: AdminAtribuirTreinosRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDietasRoute: AdminDietasRoute,
  AdminEquipamentosRoute: AdminEquipamentosRoute,
  AdminExerciciosRoute: AdminExerciciosRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPagamentosConfigRoute: AdminPagamentosConfigRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminPlanosSemanaisRoute: AdminPlanosSemanaisRoute,
  AdminPresencasRoute: AdminPresencasRoute,
  AdminProfessoresRoute: AdminProfessoresRoute,
  AdminTreinosRoute: AdminTreinosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAvaliacaoRoute: typeof AppAvaliacaoRoute
  AppDietaRoute: typeof AppDietaRoute
  AppMetasRoute: typeof AppMetasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRankingRoute: typeof AppRankingRoute
  AppTreinosRoute: typeof AppTreinosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvaliacaoRoute: AppAvaliacaoRoute,
  AppDietaRoute: AppDietaRoute,
  AppMetasRoute: AppMetasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRankingRoute: AppRankingRoute,
  AppTreinosRoute: AppTreinosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  EmBreveRoute: EmBreveRoute,
  LoginRoute: LoginRoute,
  RankingRoute: RankingRoute,
  PagarTokenRoute: PagarTokenRoute,
  ApiAdminBrandingUploadRoute: ApiAdminBrandingUploadRoute,
  ApiAdminPaymentsConfigRoute: ApiAdminPaymentsConfigRoute,
  ApiAdminPaymentsLinkRoute: ApiAdminPaymentsLinkRoute,
  ApiAdminPaymentsSubscriptionRoute: ApiAdminPaymentsSubscriptionRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiMeRolesRoute: ApiMeRolesRoute,
  ApiPublicWebhooksStoneRoute: ApiPublicWebhooksStoneRoute,
  ApiPublicPaymentsLinkTokenRoute: ApiPublicPaymentsLinkTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
