/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppTreinosRouteImport } from './routes/app.treinos'
import { Route as AppRankingRouteImport } from './routes/app.ranking'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppMetasRouteImport } from './routes/app.metas'
import { Route as AppDietaRouteImport } from './routes/app.dieta'
import { Route as AdminTreinosRouteImport } from './routes/admin.treinos'
import { Route as AdminProfessoresRouteImport } from './routes/admin.professores'
import { Route as AdminPresencasRouteImport } from './routes/admin.presencas'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminPagamentosRouteImport } from './routes/admin.pagamentos'
import { Route as AdminDietasRouteImport } from './routes/admin.dietas'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppTreinosRoute = AppTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppDietaRoute = AppDietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => AppRoute,
} as any)
const AdminTreinosRoute = AdminTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessoresRoute = AdminProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPresencasRoute = AdminPresencasRouteImport.update({
  id: '/presencas',
  path: '/presencas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDietasRoute = AdminDietasRouteImport.update({
  id: '/dietas',
  path: '/dietas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/dietas': typeof AdminDietasRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/presencas': typeof AdminPresencasRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/app/dieta': typeof AppDietaRoute
  '/app/metas': typeof AppMetasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/treinos': typeof AppTreinosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/dietas': typeof AdminDietasRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/presencas': typeof AdminPresencasRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/app/dieta': typeof AppDietaRoute
  '/app/metas': typeof AppMetasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/treinos': typeof AppTreinosRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/ranking': typeof RankingRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/dietas': typeof AdminDietasRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/presencas': typeof AdminPresencasRoute
  '/admin/professores': typeof AdminProfessoresRoute
  '/admin/treinos': typeof AdminTreinosRoute
  '/app/dieta': typeof AppDietaRoute
  '/app/metas': typeof AppMetasRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/treinos': typeof AppTreinosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/ranking'
    | '/admin/alunos'
    | '/admin/dietas'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/admin/presencas'
    | '/admin/professores'
    | '/admin/treinos'
    | '/app/dieta'
    | '/app/metas'
    | '/app/perfil'
    | '/app/ranking'
    | '/app/treinos'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/ranking'
    | '/admin/alunos'
    | '/admin/dietas'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/admin/presencas'
    | '/admin/professores'
    | '/admin/treinos'
    | '/app/dieta'
    | '/app/metas'
    | '/app/perfil'
    | '/app/ranking'
    | '/app/treinos'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/ranking'
    | '/admin/alunos'
    | '/admin/dietas'
    | '/admin/pagamentos'
    | '/admin/planos'
    | '/admin/presencas'
    | '/admin/professores'
    | '/admin/treinos'
    | '/app/dieta'
    | '/app/metas'
    | '/app/perfil'
    | '/app/ranking'
    | '/app/treinos'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RankingRoute: typeof RankingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/treinos': {
      id: '/app/treinos'
      path: '/treinos'
      fullPath: '/app/treinos'
      preLoaderRoute: typeof AppTreinosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ranking': {
      id: '/app/ranking'
      path: '/ranking'
      fullPath: '/app/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dieta': {
      id: '/app/dieta'
      path: '/dieta'
      fullPath: '/app/dieta'
      preLoaderRoute: typeof AppDietaRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/treinos': {
      id: '/admin/treinos'
      path: '/treinos'
      fullPath: '/admin/treinos'
      preLoaderRoute: typeof AdminTreinosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professores': {
      id: '/admin/professores'
      path: '/professores'
      fullPath: '/admin/professores'
      preLoaderRoute: typeof AdminProfessoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/presencas': {
      id: '/admin/presencas'
      path: '/presencas'
      fullPath: '/admin/presencas'
      preLoaderRoute: typeof AdminPresencasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dietas': {
      id: '/admin/dietas'
      path: '/dietas'
      fullPath: '/admin/dietas'
      preLoaderRoute: typeof AdminDietasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminDietasRoute: typeof AdminDietasRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminPresencasRoute: typeof AdminPresencasRoute
  AdminProfessoresRoute: typeof AdminProfessoresRoute
  AdminTreinosRoute: typeof AdminTreinosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlunosRoute: AdminAlunosRoute,
  AdminDietasRoute: AdminDietasRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminPresencasRoute: AdminPresencasRoute,
  AdminProfessoresRoute: AdminProfessoresRoute,
  AdminTreinosRoute: AdminTreinosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppDietaRoute: typeof AppDietaRoute
  AppMetasRoute: typeof AppMetasRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRankingRoute: typeof AppRankingRoute
  AppTreinosRoute: typeof AppTreinosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDietaRoute: AppDietaRoute,
  AppMetasRoute: AppMetasRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRankingRoute: AppRankingRoute,
  AppTreinosRoute: AppTreinosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RankingRoute: RankingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
